### ISSUE TITLE
Update versions for material-ui branch.

### ISSUE THREAD

**Issue by jasonhett** [Robert-W/esri-redux#9]
Current package versions allow for a similar issue to:
https://github.com/prescottprue/generator-react-firebase/issues/27

**Comment by Robert-W** [comment]
Ah ok, I'll pull in the latest version, the material ui branch is a little outdated and needs to be updated anyway.  You coming to wine in the woods?

**Comment by Robert-W** [comment]
Fixed, could use some polishing in the styles and themes but the material-ui branch is now up to date with updated tests as well, and dist script still works
